version: '3.9'

services:
  go-app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=postgres://postgres:password@postgres:5432/mydb
      - MONGO_URL=mongodb://mongodb:27017/mydb
    depends_on:
      - postgres
      - mongodb
    entrypoint:
      - /wait-for-it.sh
      - postgres:5432
      - --
      - mongodb:27017
      - --
      - ./main

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js

volumes:
  postgres-data:
  mongodb-data:
